# ABOUTME: msmtp email client configuration for maintenance notifications
# ABOUTME: Integrates with macOS Keychain for secure credential storage (Feature 06.5)
{
  config,
  pkgs,
  lib,
  userConfig,
  ...
}: {
  # =============================================================================
  # MSMTP SMTP CLIENT CONFIGURATION (Story 06.5-001)
  # =============================================================================
  # Lightweight SMTP client for sending email notifications from maintenance jobs
  # Reference: https://marlam.de/msmtp/
  #
  # Note: We generate the config manually via xdg.configFile because Home Manager's
  # programs.msmtp module requires accounts.email.accounts which is complex to set up.
  # This simpler approach just installs msmtp and generates ~/.config/msmtp/config

  # Install msmtp package
  home.packages = with pkgs; [
    msmtp
  ];

  # Generate msmtp configuration file
  # Uses macOS Keychain for secure password storage via passwordeval
  xdg.configFile."msmtp/config".text = ''
    # msmtp configuration for Gandi email
    # Generated by nix-install (Feature 06.5)
    #
    # IMPORTANT: Before using, store your password in Keychain:
    #   ./scripts/setup-msmtp-keychain.sh
    # Or manually:
    #   security add-generic-password -a "${userConfig.email}" -s "msmtp-gandi" -w

    # Default settings
    defaults
    auth           on
    tls            on
    tls_starttls   on
    tls_trust_file /etc/ssl/cert.pem
    logfile        ${config.home.homeDirectory}/.local/log/msmtp.log

    # Gandi account
    account        gandi
    host           mail.gandi.net
    port           587
    from           ${userConfig.email}
    user           ${userConfig.email}
    passwordeval   "security find-generic-password -a '${userConfig.email}' -s 'msmtp-gandi' -w 2>/dev/null"

    # Set default account
    account default : gandi
  '';

  # Ensure log directory exists for msmtp logging
  home.activation.createMsmtpLogDir = lib.hm.dag.entryAfter ["writeBoundary"] ''
    run mkdir -p $HOME/.local/log
  '';
}
