#!/usr/bin/env bash
#===============================================================================
# CX11 Dev Server Bootstrap Script
# 
# Usage: curl -fsSL https://raw.githubusercontent.com/YOUR_USER/YOUR_REPO/main/bootstrap-dev-server.sh | bash
#
# Idempotent: Safe to run multiple times
# Requirements: Fresh Ubuntu 24.04 server with sudo access
#===============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

#===============================================================================
# Configuration - Edit these for your setup
#===============================================================================
DEV_USER="${DEV_USER:-$(whoami)}"
SSH_PORT="${SSH_PORT:-22}"
MOSH_PORT_START="${MOSH_PORT_START:-60000}"
MOSH_PORT_END="${MOSH_PORT_END:-60010}"
FLAKE_REPO="${FLAKE_REPO:-}"  # Optional: github:user/repo for your flake

#===============================================================================
# Preflight Checks
#===============================================================================
preflight_checks() {
    log_info "Running preflight checks..."
    
    # Check Ubuntu version
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        if [[ "$ID" != "ubuntu" ]]; then
            log_error "This script is designed for Ubuntu. Detected: $ID"
            exit 1
        fi
        log_ok "Detected $PRETTY_NAME"
    fi
    
    # Check sudo access
    if ! sudo -n true 2>/dev/null; then
        log_warn "Script requires sudo access. You may be prompted for password."
    fi
    
    # Check internet connectivity
    if ! ping -c 1 github.com &>/dev/null; then
        log_error "No internet connectivity"
        exit 1
    fi
    log_ok "Internet connectivity verified"
}

#===============================================================================
# System Updates & Base Packages
#===============================================================================
install_base_packages() {
    log_info "Updating system and installing base packages..."
    
    export DEBIAN_FRONTEND=noninteractive
    
    sudo apt-get update -qq
    sudo apt-get upgrade -y -qq
    
    # Minimal base packages (most tools will come from Nix)
    sudo apt-get install -y -qq \
        curl \
        git \
        xz-utils \
        ufw \
        fail2ban \
        mosh \
        unattended-upgrades
    
    log_ok "Base packages installed"
}

#===============================================================================
# SSH Hardening
#===============================================================================
harden_ssh() {
    log_info "Hardening SSH configuration..."
    
    local SSH_HARDENING_FILE="/etc/ssh/sshd_config.d/99-hardening.conf"
    
    # Only create if doesn't exist or force update
    if [[ ! -f "$SSH_HARDENING_FILE" ]] || [[ "${FORCE_SSH_UPDATE:-}" == "true" ]]; then
        sudo tee "$SSH_HARDENING_FILE" > /dev/null << 'SSHEOF'
# SSH Hardening Configuration
# Generated by bootstrap-dev-server.sh

# Disable root login
PermitRootLogin no

# Key-based authentication only
PasswordAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey

# Disable unused authentication methods
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no

# Session limits
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30

# Forwarding settings
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding yes

# Strong algorithms only
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes256-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Logging
LogLevel VERBOSE
PrintLastLog yes

# Idle timeout (optional - 10 min)
ClientAliveInterval 300
ClientAliveCountMax 2
SSHEOF
        
        # Validate SSH config before restart
        if sudo sshd -t; then
            sudo systemctl reload ssh || sudo systemctl reload sshd
            log_ok "SSH hardening applied"
        else
            log_error "SSH config validation failed! Reverting..."
            sudo rm -f "$SSH_HARDENING_FILE"
            exit 1
        fi
    else
        log_ok "SSH hardening already configured"
    fi
}

#===============================================================================
# Regenerate Host Keys (Optional - only on fresh install)
#===============================================================================
regenerate_host_keys() {
    if [[ "${REGEN_HOST_KEYS:-}" == "true" ]]; then
        log_info "Regenerating SSH host keys..."
        
        sudo rm -f /etc/ssh/ssh_host_*
        sudo ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""
        sudo ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ""
        
        # Filter weak DH moduli
        awk '$5 >= 3071' /etc/ssh/moduli | sudo tee /etc/ssh/moduli.tmp > /dev/null
        sudo mv /etc/ssh/moduli.tmp /etc/ssh/moduli
        
        sudo systemctl reload ssh || sudo systemctl reload sshd
        log_ok "SSH host keys regenerated"
    fi
}

#===============================================================================
# Firewall Configuration
#===============================================================================
configure_firewall() {
    log_info "Configuring UFW firewall..."
    
    # Reset if already enabled (idempotent)
    sudo ufw --force reset > /dev/null
    
    sudo ufw default deny incoming
    sudo ufw default allow outgoing
    
    # SSH
    sudo ufw allow "$SSH_PORT"/tcp comment 'SSH'
    
    # Mosh UDP ports
    sudo ufw allow "${MOSH_PORT_START}:${MOSH_PORT_END}"/udp comment 'Mosh'
    
    # Enable firewall
    sudo ufw --force enable
    
    log_ok "Firewall configured (SSH: $SSH_PORT, Mosh: $MOSH_PORT_START-$MOSH_PORT_END)"
}

#===============================================================================
# Fail2Ban Configuration
#===============================================================================
configure_fail2ban() {
    log_info "Configuring Fail2Ban..."
    
    sudo tee /etc/fail2ban/jail.local > /dev/null << 'F2BEOF'
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 3
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 24h
F2BEOF

    sudo systemctl enable fail2ban
    sudo systemctl restart fail2ban
    
    log_ok "Fail2Ban configured"
}

#===============================================================================
# Install Nix (Determinate Systems Installer)
#===============================================================================
install_nix() {
    log_info "Installing Nix..."
    
    if command -v nix &>/dev/null; then
        log_ok "Nix already installed: $(nix --version)"
        return 0
    fi
    
    # Determinate Systems installer - enables flakes by default
    curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | \
        sh -s -- install --no-confirm
    
    # Source Nix in current shell
    if [[ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
        . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    fi
    
    log_ok "Nix installed: $(nix --version)"
}

#===============================================================================
# Create Dev Environment Flake
#===============================================================================
create_dev_flake() {
    log_info "Creating dev environment flake..."
    
    local FLAKE_DIR="$HOME/.config/nix-dev-env"
    
    mkdir -p "$FLAKE_DIR"
    
    # Create flake.nix
    cat > "$FLAKE_DIR/flake.nix" << 'FLAKEEOF'
{
  description = "CX11 Dev Server Environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    
    # Claude Code with auto-updates
    claude-code-nix = {
      url = "github:sadjow/claude-code-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, claude-code-nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
      in
      {
        # Default dev shell
        devShells.default = pkgs.mkShell {
          name = "dev-server";
          
          buildInputs = [
            # Claude Code
            claude-code-nix.packages.${system}.claude-code
            
            # Core CLI tools
            pkgs.git
            pkgs.curl
            pkgs.wget
            pkgs.jq
            pkgs.yq
            pkgs.ripgrep
            pkgs.fd
            pkgs.bat
            pkgs.eza
            pkgs.fzf
            pkgs.tree
            pkgs.htop
            pkgs.btop
            
            # Editors
            pkgs.neovim
            pkgs.helix
            
            # Shell enhancements
            pkgs.tmux
            pkgs.zoxide
            pkgs.starship
            pkgs.direnv
            
            # Python
            pkgs.python312
            pkgs.python312Packages.pip
            pkgs.python312Packages.virtualenv
            pkgs.uv  # Fast Python package installer
            
            # Node.js
            pkgs.nodejs_22
            
            # Container tools
            pkgs.podman
            pkgs.podman-compose
            
            # Network tools
            pkgs.httpie
            pkgs.websocat
            
            # Development utilities
            pkgs.gh  # GitHub CLI
            pkgs.lazygit
            pkgs.delta  # Git diff viewer
          ];
          
          shellHook = ''
            export EDITOR=nvim
            export VISUAL=nvim
            
            # Starship prompt
            eval "$(starship init bash)"
            
            # Zoxide (smart cd)
            eval "$(zoxide init bash)"
            
            # Direnv
            eval "$(direnv hook bash)"
            
            echo ""
            echo "🚀 Dev Server Environment Loaded"
            echo "   Claude: $(claude --version 2>/dev/null || echo 'run: claude')"
            echo "   Python: $(python3 --version)"
            echo "   Node:   $(node --version)"
            echo ""
          '';
        };
        
        # Minimal shell (just Claude + basics)
        devShells.minimal = pkgs.mkShell {
          name = "minimal";
          buildInputs = [
            claude-code-nix.packages.${system}.claude-code
            pkgs.git
            pkgs.curl
            pkgs.jq
            pkgs.ripgrep
            pkgs.neovim
          ];
        };
        
        # Python-focused shell
        devShells.python = pkgs.mkShell {
          name = "python-dev";
          buildInputs = [
            claude-code-nix.packages.${system}.claude-code
            pkgs.python312
            pkgs.python312Packages.pip
            pkgs.python312Packages.virtualenv
            pkgs.uv
            pkgs.ruff
            pkgs.git
            pkgs.neovim
          ];
        };
      });
}
FLAKEEOF

    # Initialize git repo for flake (required)
    cd "$FLAKE_DIR"
    if [[ ! -d .git ]]; then
        git init -q
    fi
    git add -A
    
    log_ok "Dev flake created at $FLAKE_DIR"
}

#===============================================================================
# Shell Integration
#===============================================================================
setup_shell_integration() {
    log_info "Setting up shell integration..."
    
    local FLAKE_DIR="$HOME/.config/nix-dev-env"
    local BASHRC="$HOME/.bashrc"
    local MARKER="# >>> nix-dev-env >>>"
    
    # Check if already configured
    if grep -q "$MARKER" "$BASHRC" 2>/dev/null; then
        log_ok "Shell integration already configured"
        return 0
    fi
    
    cat >> "$BASHRC" << SHELLEOF

$MARKER
# Nix daemon
if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

# Auto-enter dev environment
dev() {
    nix develop "$FLAKE_DIR#\${1:-default}" -c \$SHELL
}

# Shortcut aliases
alias d='dev'
alias dm='dev minimal'
alias dp='dev python'

# Update dev environment
dev-update() {
    cd "$FLAKE_DIR" && nix flake update && cd -
}

# Quick Claude access (runs in minimal env if not in dev shell)
claude-quick() {
    if command -v claude &>/dev/null; then
        claude "\$@"
    else
        nix run "$FLAKE_DIR#minimal" -- claude "\$@"
    fi
}
# <<< nix-dev-env <<<
SHELLEOF

    log_ok "Shell integration configured"
    log_info "Run 'source ~/.bashrc' or reconnect to activate"
}

#===============================================================================
# Create CLAUDE.md Template
#===============================================================================
create_claude_md() {
    log_info "Creating CLAUDE.md template..."
    
    local CLAUDE_MD="$HOME/CLAUDE.md"
    
    if [[ -f "$CLAUDE_MD" ]]; then
        log_ok "CLAUDE.md already exists"
        return 0
    fi
    
    cat > "$CLAUDE_MD" << 'CLAUDEEOF'
# CLAUDE.md - Project Instructions

## Environment
- OS: Ubuntu 24.04 LTS
- Shell: Bash with Nix dev environment
- Editor: Neovim preferred

## Development Workflow
1. Enter dev environment: `dev` or `nix develop`
2. Use `lazygit` for git operations
3. Use `gh` for GitHub CLI operations

## Code Standards
- Python: Use `ruff` for linting, `uv` for package management
- Follow conventional commits
- Write tests for new features

## Project Structure
```
~/projects/
├── project-name/
│   ├── CLAUDE.md      # Project-specific instructions
│   ├── flake.nix      # Optional project-specific flake
│   └── ...
```

## Commands Reference
- `dev` - Enter full dev environment
- `dm` - Enter minimal environment  
- `dp` - Enter Python environment
- `dev-update` - Update Nix flake dependencies
- `claude` - Start Claude Code session
CLAUDEEOF

    log_ok "CLAUDE.md template created at $CLAUDE_MD"
}

#===============================================================================
# Build Initial Nix Environment (warm cache)
#===============================================================================
warm_nix_cache() {
    log_info "Building Nix environment (this may take a few minutes on first run)..."
    
    local FLAKE_DIR="$HOME/.config/nix-dev-env"
    
    # Source Nix if not already available
    if ! command -v nix &>/dev/null; then
        if [[ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]]; then
            . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
        fi
    fi
    
    # Build the default shell (downloads and caches all dependencies)
    cd "$FLAKE_DIR"
    nix build .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default --no-link
    
    log_ok "Nix environment built and cached"
}

#===============================================================================
# Print Summary
#===============================================================================
print_summary() {
    local IP_ADDR
    IP_ADDR=$(hostname -I | awk '{print $1}')
    
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  ✅ Dev Server Bootstrap Complete!${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  ${BLUE}Connection:${NC}"
    echo -e "    SSH:  ${YELLOW}ssh $DEV_USER@$IP_ADDR${NC}"
    echo -e "    Mosh: ${YELLOW}mosh $DEV_USER@$IP_ADDR${NC}"
    echo ""
    echo -e "  ${BLUE}Quick Start:${NC}"
    echo -e "    1. Reconnect or run: ${YELLOW}source ~/.bashrc${NC}"
    echo -e "    2. Enter dev environment: ${YELLOW}dev${NC}"
    echo -e "    3. Start Claude: ${YELLOW}claude${NC}"
    echo ""
    echo -e "  ${BLUE}Available Environments:${NC}"
    echo -e "    ${YELLOW}dev${NC}        - Full dev environment"
    echo -e "    ${YELLOW}dev minimal${NC} - Just Claude + basics"
    echo -e "    ${YELLOW}dev python${NC}  - Python-focused environment"
    echo ""
    echo -e "  ${BLUE}Maintenance:${NC}"
    echo -e "    ${YELLOW}dev-update${NC}  - Update all Nix packages"
    echo ""
    echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
}

#===============================================================================
# Main
#===============================================================================
main() {
    echo ""
    echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║       CX11 Dev Server Bootstrap Script                        ║${NC}"
    echo -e "${BLUE}║       Ubuntu 24.04 + Nix Flakes + Claude Code                 ║${NC}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    preflight_checks
    install_base_packages
    harden_ssh
    regenerate_host_keys
    configure_firewall
    configure_fail2ban
    install_nix
    create_dev_flake
    setup_shell_integration
    create_claude_md
    warm_nix_cache
    print_summary
}

# Run main function
main "$@"
