# ABOUTME: rsync backup LaunchAgent for TerraMaster NAS
# ABOUTME: Generates config from rsync-backup-config.nix and schedules automated backups
# ABOUTME: Scripts are installed to ~/.local/bin to avoid macOS TCC restrictions
{
  config,
  pkgs,
  lib,
  userConfig,
  ...
}: let
  # Import the rsync backup configuration if it exists
  rsyncConfigPath = ../rsync-backup-config.nix;
  rsyncConfigExists = builtins.pathExists rsyncConfigPath;
  rsyncConfig =
    if rsyncConfigExists
    then import rsyncConfigPath
    else null;

  # Scripts directory (TCC-safe location)
  scriptsDir = "/Users/${userConfig.username}/.local/bin";

  # Generate the jobs.conf content from the Nix config
  generateJobsConf = config: let
    # Convert a job to the pipe-delimited format: name|source|share|destination|excludes
    # If job doesn't have a share, use defaultShare
    jobToLine = job: let
      share = job.share or config.defaultShare or "backup";
    in "${job.name}|${job.source}|${share}|${job.destination}|${lib.concatStringsSep "," job.excludes}";
    jobLines = map jobToLine config.jobs;
  in ''
    # Auto-generated by nix-darwin from rsync-backup-config.nix
    # DO NOT EDIT - changes will be overwritten on rebuild
    # Generated: $(date)

    # NAS connection settings
    NAS_HOST="${config.nasHost}"
    DEFAULT_SHARE="${config.defaultShare or "backup"}"
    SMB_USERNAME="${config.smbUsername or userConfig.username}"

    # Notification settings
    NOTIFY_ON_FAILURE="${
      if config.notifyOnFailure
      then "true"
      else "false"
    }"
    NOTIFICATION_EMAIL="${userConfig.notificationEmail}"

    # Backup jobs (pipe-delimited: name|source|share|destination|excludes)
    JOBS=(
    ${lib.concatMapStringsSep "\n" (line: "  \"${line}\"") jobLines}
    )
  '';
in
  lib.mkIf rsyncConfigExists {
    # ===========================================================================
    # RSYNC BACKUP CONFIG GENERATION
    # ===========================================================================
    # Generate the jobs.conf file in ~/.config/rsync-backup/
    # This file is read by the rsync-backup.sh script
    #
    # NOTE: Must use postActivation (a hardcoded name that nix-darwin runs)
    # Custom activation script names are NOT executed automatically
    # See: https://github.com/nix-darwin/nix-darwin/issues/663

    system.activationScripts.postActivation.text = lib.mkAfter ''
      # ========================================================================
      # RSYNC BACKUP CONFIGURATION
      # ========================================================================
      echo "Generating rsync backup configuration..."
      CONFIG_DIR="/Users/${userConfig.username}/.config/rsync-backup"
      mkdir -p "$CONFIG_DIR"
      cat > "$CONFIG_DIR/jobs.conf" << 'RSYNC_CONFIG_EOF'
${generateJobsConf rsyncConfig}
RSYNC_CONFIG_EOF
      chmod 600 "$CONFIG_DIR/jobs.conf"
      chown -R ${userConfig.username}:staff "$CONFIG_DIR"
      echo "✓ rsync backup config generated at $CONFIG_DIR/jobs.conf"

      # Copy rsync-backup.sh to TCC-safe location
      SCRIPT_SRC="/Users/${userConfig.username}/${userConfig.directories.dotfiles}/scripts/rsync-backup.sh"
      SCRIPT_DST="${scriptsDir}/rsync-backup.sh"
      if [[ -f "$SCRIPT_SRC" ]]; then
        cp "$SCRIPT_SRC" "$SCRIPT_DST"
        chmod 755 "$SCRIPT_DST"
        chown ${userConfig.username}:staff "$SCRIPT_DST"
        echo "✓ rsync-backup.sh installed to $SCRIPT_DST"
      else
        echo "⚠ rsync-backup.sh not found at $SCRIPT_SRC"
      fi
    '';

    # ===========================================================================
    # RSYNC BACKUP LAUNCHAGENT
    # ===========================================================================
    # Scheduled backup to TerraMaster NAS
    # Runs at the time specified in rsync-backup-config.nix (default: 2 AM daily)

    launchd.user.agents.rsync-backup = {
      serviceConfig = {
        # Command to execute the backup script
        ProgramArguments = [
          "/bin/bash"
          "-c"
          ''
            # Set up environment
            export NOTIFICATION_EMAIL="${userConfig.notificationEmail}"
            export PATH="/etc/profiles/per-user/${userConfig.username}/bin:/run/current-system/sw/bin:/usr/bin:/bin"
            export HOME="/Users/${userConfig.username}"
            export SCRIPTS_DIR="${scriptsDir}"

            # Run the rsync backup script
            if [[ -x "${scriptsDir}/rsync-backup.sh" ]]; then
              "${scriptsDir}/rsync-backup.sh"
            else
              echo "ERROR: rsync-backup.sh not found at ${scriptsDir}/rsync-backup.sh"
              echo "Run 'rebuild' to install the script"
              exit 1
            fi
          ''
        ];

        # Schedule from config (default: 2 AM daily)
        StartCalendarInterval = [
          {
            Hour = rsyncConfig.schedule.Hour;
            Minute = rsyncConfig.schedule.Minute;
          }
        ];

        # Logging configuration
        StandardOutPath = "/tmp/rsync-backup.log";
        StandardErrorPath = "/tmp/rsync-backup.err";

        # Environment variables
        EnvironmentVariables = {
          PATH = "/etc/profiles/per-user/${userConfig.username}/bin:/run/current-system/sw/bin:/usr/bin:/bin";
          HOME = "/Users/${userConfig.username}";
          NOTIFICATION_EMAIL = userConfig.notificationEmail;
        };

        # Don't run on load, wait for scheduled time
        RunAtLoad = false;
        KeepAlive = false;
      };
    };
  }
