# ABOUTME: rsync backup LaunchAgents for TerraMaster NAS
# ABOUTME: Generates config from rsync-backup-config.nix and schedules automated backups
# ABOUTME: Creates separate LaunchAgents for daily and weekly jobs
# ABOUTME: Scripts are installed to ~/.local/bin to avoid macOS TCC restrictions
{
  config,
  pkgs,
  lib,
  userConfig,
  ...
}: let
  # Import the rsync backup configuration if it exists
  rsyncConfigPath = ../rsync-backup-config.nix;
  rsyncConfigExists = builtins.pathExists rsyncConfigPath;
  rsyncConfig =
    if rsyncConfigExists
    then import rsyncConfigPath
    else null;

  # Scripts directory (TCC-safe location)
  scriptsDir = "/Users/${userConfig.username}/.local/bin";

  # Filter jobs by schedule
  dailyJobs = lib.filter (job: (job.schedule or "daily") == "daily") rsyncConfig.jobs;
  weeklyJobs = lib.filter (job: (job.schedule or "daily") == "weekly") rsyncConfig.jobs;

  # Generate the jobs.conf content for a list of jobs
  generateJobsConf = jobs: ''
    # Auto-generated by nix-darwin from rsync-backup-config.nix
    # DO NOT EDIT - changes will be overwritten on rebuild
    # Generated: $(date)

    # NAS connection settings
    NAS_HOST="${rsyncConfig.nasHost}"
    DEFAULT_SHARE="${rsyncConfig.defaultShare or "backup"}"
    SMB_USERNAME="${rsyncConfig.smbUsername or userConfig.username}"

    # Notification settings
    NOTIFY_ON_FAILURE="${
      if rsyncConfig.notifyOnFailure
      then "true"
      else "false"
    }"
    NOTIFICATION_EMAIL="${userConfig.notificationEmail}"

    # Backup jobs (pipe-delimited: name|source|share|destination|excludes)
    JOBS=(
    ${lib.concatMapStringsSep "\n" (job: let
        share = job.share or rsyncConfig.defaultShare or "backup";
      in "  \"${job.name}|${job.source}|${share}|${job.destination}|${lib.concatStringsSep "," job.excludes}\"") jobs}
    )
  '';

  # Create a LaunchAgent for a schedule
  mkBackupAgent = {
    name,
    schedule,
    configFile,
    logSuffix,
  }: {
    serviceConfig = {
      ProgramArguments = [
        "/bin/bash"
        "-c"
        ''
          # Set up environment
          export NOTIFICATION_EMAIL="${userConfig.notificationEmail}"
          export PATH="/etc/profiles/per-user/${userConfig.username}/bin:/run/current-system/sw/bin:/usr/bin:/bin"
          export HOME="/Users/${userConfig.username}"
          export SCRIPTS_DIR="${scriptsDir}"
          export CONFIG_FILE="${configFile}"

          # Run the rsync backup script
          if [[ -x "${scriptsDir}/rsync-backup.sh" ]]; then
            "${scriptsDir}/rsync-backup.sh"
          else
            echo "ERROR: rsync-backup.sh not found at ${scriptsDir}/rsync-backup.sh"
            echo "Run 'rebuild' to install the script"
            exit 1
          fi
        ''
      ];

      StartCalendarInterval = [schedule];

      StandardOutPath = "/tmp/rsync-backup${logSuffix}.log";
      StandardErrorPath = "/tmp/rsync-backup${logSuffix}.err";

      EnvironmentVariables = {
        PATH = "/etc/profiles/per-user/${userConfig.username}/bin:/run/current-system/sw/bin:/usr/bin:/bin";
        HOME = "/Users/${userConfig.username}";
        NOTIFICATION_EMAIL = userConfig.notificationEmail;
        CONFIG_FILE = configFile;
      };

      RunAtLoad = false;
      KeepAlive = false;
    };
  };
in
  lib.mkIf rsyncConfigExists {
    # ===========================================================================
    # RSYNC BACKUP CONFIG GENERATION
    # ===========================================================================

    system.activationScripts.postActivation.text = lib.mkAfter ''
      # ========================================================================
      # RSYNC BACKUP CONFIGURATION
      # ========================================================================
      echo "Generating rsync backup configuration..."
      CONFIG_DIR="/Users/${userConfig.username}/.config/rsync-backup"
      mkdir -p "$CONFIG_DIR"

      # Generate daily jobs config
      cat > "$CONFIG_DIR/jobs-daily.conf" << 'RSYNC_DAILY_EOF'
${generateJobsConf dailyJobs}
RSYNC_DAILY_EOF
      chmod 600 "$CONFIG_DIR/jobs-daily.conf"
      echo "✓ rsync daily config: ${toString (builtins.length dailyJobs)} job(s)"

      # Generate weekly jobs config
      cat > "$CONFIG_DIR/jobs-weekly.conf" << 'RSYNC_WEEKLY_EOF'
${generateJobsConf weeklyJobs}
RSYNC_WEEKLY_EOF
      chmod 600 "$CONFIG_DIR/jobs-weekly.conf"
      echo "✓ rsync weekly config: ${toString (builtins.length weeklyJobs)} job(s)"

      chown -R ${userConfig.username}:staff "$CONFIG_DIR"

      # Copy rsync-backup.sh to TCC-safe location
      SCRIPT_SRC="/Users/${userConfig.username}/${userConfig.directories.dotfiles}/scripts/rsync-backup.sh"
      SCRIPT_DST="${scriptsDir}/rsync-backup.sh"
      if [[ -f "$SCRIPT_SRC" ]]; then
        cp "$SCRIPT_SRC" "$SCRIPT_DST"
        chmod 755 "$SCRIPT_DST"
        chown ${userConfig.username}:staff "$SCRIPT_DST"
        echo "✓ rsync-backup.sh installed to $SCRIPT_DST"
      else
        echo "⚠ rsync-backup.sh not found at $SCRIPT_SRC"
      fi
    '';

    # ===========================================================================
    # RSYNC BACKUP LAUNCHAGENTS
    # ===========================================================================

    launchd.user.agents = {
      # Daily backup (iCloud, etc.) - runs at 2 AM every day
      rsync-backup-daily = lib.mkIf (builtins.length dailyJobs > 0) (mkBackupAgent {
        name = "daily";
        schedule = {
          Hour = rsyncConfig.defaultSchedule.Hour;
          Minute = rsyncConfig.defaultSchedule.Minute;
        };
        configFile = "/Users/${userConfig.username}/.config/rsync-backup/jobs-daily.conf";
        logSuffix = "-daily";
      });

      # Weekly backup (Photos, etc.) - runs at 2 AM every Sunday
      rsync-backup-weekly = lib.mkIf (builtins.length weeklyJobs > 0) (mkBackupAgent {
        name = "weekly";
        schedule = {
          Hour = rsyncConfig.defaultSchedule.Hour;
          Minute = rsyncConfig.defaultSchedule.Minute;
          Weekday = 0; # Sunday
        };
        configFile = "/Users/${userConfig.username}/.config/rsync-backup/jobs-weekly.conf";
        logSuffix = "-weekly";
      });
    };
  }
