# ABOUTME: SMB NAS share mounting via a user LaunchAgent running mount_smbfs
# ABOUTME: Replaces autofs, which macOS 26 silently stopped honoring (issue #407)
# ABOUTME: Password read from ~/.config/smb-nas/password at mount time, never persisted
#
# WHY NOT AUTOFS ANYMORE:
# macOS 26 no longer honors custom /etc/auto_master maps. `automount -vc` exits
# 0, prints nothing, and creates no trigger directories, so /Volumes/<Share>
# never mounted while every rebuild cheerfully reported success. Apple-internal
# automount uses (Time Machine's /Volumes/.timemachine) still work; custom maps
# do not. There is no configuration that makes the old mechanism work, so the
# mechanism is gone.
#
# IMPORTANT: This module does NOT touch /etc/synthetic.conf
# That file is managed by nix-darwin for the Nix store mount point.
#
# SETUP (one-time):
#   1. Create password file (not tracked in git):
#      mkdir -p ~/.config/smb-nas
#      echo "YOUR_NAS_PASSWORD" > ~/.config/smb-nas/password
#      chmod 600 ~/.config/smb-nas/password
#
#   2. Run rebuild to apply configuration
#
{
  config,
  pkgs,
  lib,
  userConfig,
  ...
}:
let
  # NAS configuration - centralized for easy modification
  nasConfig = {
    host = "tnas.local"; # NAS hostname (mDNS)
    hostname = "tnas.local"; # mDNS hostname
    username = userConfig.username; # SMB username (from user-config.nix)
    shares = [
      "Photos" # Photo backup share
      "icloud" # iCloud Drive backup share
      "calibre" # Calibre ebook library backup share
    ];
  };

  homeDir = "/Users/${userConfig.username}";

  # Password file location (not in git, user must create manually)
  passwordFile = "${homeDir}/.config/smb-nas/password";

  configDir = "${homeDir}/.config/smb-nas";
  configFile = "${configDir}/shares.conf";

  # Scripts live in ~/.local/bin to avoid macOS TCC restrictions on ~/Documents
  scriptsDir = "${homeDir}/.local/bin";
  mountScript = "${scriptsDir}/smb-mount-nas.sh";

  # Mount under the user's home rather than /Volumes: a user LaunchAgent cannot
  # create directories at the root of /Volumes without admin-group juggling,
  # and ownership of the mount point stays unambiguous here.
  mountRoot = "${homeDir}/NAS";

  # /sbin and /usr/sbin are on PATH for mount_smbfs; /usr/bin supplies nc.
  agentPath = "/etc/profiles/per-user/${userConfig.username}/bin:/run/current-system/sw/bin:/usr/sbin:/sbin:/usr/bin:/bin";

in
{
  # ===========================================================================
  # CONFIG GENERATION VIA ACTIVATION SCRIPT
  # ===========================================================================
  # The activation script generates the share list consumed by
  # scripts/smb-mount-nas.sh and installs that script into the TCC-safe
  # ~/.local/bin, mirroring darwin/rsync-backup.nix.
  #
  # No credential is written anywhere: the mount script reads
  # ${passwordFile} at mount time and URL-encodes it in memory.

  system.activationScripts.postActivation.text = lib.mkAfter ''
    # ========================================================================
    # SMB NAS MOUNT CONFIGURATION
    # ========================================================================
    echo "Configuring SMB NAS mounts..."

    # --- Retire the dead autofs configuration ---
    # Earlier releases wrote the NAS password into /etc/auto_smb. That map is
    # inert on macOS 26 but the plaintext credential in it is not, so remove it
    # on the first rebuild after the switch.
    if [[ -f /etc/auto_smb ]]; then
      rm -f /etc/auto_smb
      echo "  Removed stale /etc/auto_smb (autofs no longer used)"
    fi
    if [[ -f /etc/auto_master ]] && grep -q 'auto_smb' /etc/auto_master; then
      sed -i.bak '/auto_smb/d' /etc/auto_master && rm -f /etc/auto_master.bak
      automount -vc >/dev/null 2>&1 || true
      echo "  Removed auto_smb entry from /etc/auto_master"
    fi

    # --- Generate the share list ---
    SMB_CONFIG_DIR="${configDir}"
    mkdir -p "$SMB_CONFIG_DIR"
    cat > "${configFile}" << 'SMB_SHARES_EOF'
    # Auto-generated by nix-darwin from darwin/smb-automount.nix
    # DO NOT EDIT - changes will be overwritten on rebuild
    NAS_HOST="${nasConfig.host}"
    SMB_USERNAME="${nasConfig.username}"
    MOUNT_ROOT="${mountRoot}"
    SHARES=(
    ${lib.concatMapStringsSep "\n" (share: "  \"${share}\"") nasConfig.shares}
    )
    SMB_SHARES_EOF
    chmod 600 "${configFile}"
    chown -R ${userConfig.username}:staff "$SMB_CONFIG_DIR"

    # --- Mount root ---
    mkdir -p "${mountRoot}"
    chown ${userConfig.username}:staff "${mountRoot}"

    # --- Install the mount script to the TCC-safe location ---
    SMB_SCRIPT_SRC="${homeDir}/${userConfig.directories.dotfiles}/scripts/smb-mount-nas.sh"
    if [[ -f "$SMB_SCRIPT_SRC" ]]; then
      mkdir -p "${scriptsDir}"
      cp "$SMB_SCRIPT_SRC" "${mountScript}"
      chmod 755 "${mountScript}"
      chown ${userConfig.username}:staff "${mountScript}"
      echo "✓ smb-mount-nas.sh installed to ${mountScript}"
    else
      echo "⚠ smb-mount-nas.sh not found at $SMB_SCRIPT_SRC"
    fi

    if [[ ! -f "${passwordFile}" ]]; then
      echo ""
      echo "  WARNING: Password file not found: ${passwordFile}"
      echo "  NAS shares will NOT mount without credentials."
      echo ""
      echo "  Create the password file (one-time setup):"
      echo "    mkdir -p ~/.config/smb-nas"
      echo "    echo 'YOUR_NAS_PASSWORD' > ~/.config/smb-nas/password"
      echo "    chmod 600 ~/.config/smb-nas/password"
      echo ""
    fi

    echo "SMB NAS mount configuration complete"
    echo "  Shares: ${lib.concatStringsSep ", " (map (s: "${mountRoot}/${s}") nasConfig.shares)}"
    echo "  Test with: ${mountScript}"
  '';

  # ===========================================================================
  # MOUNT LAUNCHAGENT
  # ===========================================================================
  # RunAtLoad mounts at login; StartInterval retries periodically so the shares
  # come back after the laptop rejoins the network. Deliberately NOT KeepAlive:
  # the script is a one-shot that exits, and KeepAlive would respawn it in a
  # tight loop whenever the NAS is off.

  launchd.user.agents.smb-mount-nas = {
    serviceConfig = {
      Label = "org.nixos.smb-mount-nas";
      ProgramArguments = [
        "/bin/bash"
        "-c"
        ''
          SCRIPT="${mountScript}"
          if [[ -x "$SCRIPT" ]]; then
            "$SCRIPT"
          else
            echo "smb-mount-nas script not found: $SCRIPT" >> /tmp/smb-mount-nas.err
            exit 1
          fi
        ''
      ];
      RunAtLoad = true;
      StartInterval = 900; # Retry every 15 minutes
      KeepAlive = false;
      StandardOutPath = "/tmp/smb-mount-nas.log";
      StandardErrorPath = "/tmp/smb-mount-nas.err";
      EnvironmentVariables = {
        PATH = agentPath;
        HOME = homeDir;
      };
      Umask = 63; # Decimal representation of 0077 - owner-only mount points
    };
  };

  # ===========================================================================
  # ASSERTIONS
  # ===========================================================================

  assertions = [
    {
      assertion = builtins.length nasConfig.shares > 0;
      message = "At least one SMB share must be configured in smb-automount.nix";
    }
  ];
}
