#!/usr/bin/env bash
# ABOUTME: Mounts the configured NAS SMB shares via mount_smbfs (issue #407)
# ABOUTME: Replaces autofs, which macOS 26 silently stopped honoring for custom maps
# ABOUTME: Idempotent - skips already-mounted shares, soft-fails when the NAS is offline
# ABOUTME: Config is generated by darwin/smb-automount.nix into ~/.config/smb-nas/shares.conf

set -euo pipefail

# =============================================================================
# CONFIGURATION
# =============================================================================

# Both paths are seams: the LaunchAgent relies on the defaults, tests point
# them at fixtures.
CONFIG_FILE="${SMB_MOUNT_CONFIG:-${HOME}/.config/smb-nas/shares.conf}"
PASSWORD_FILE="${SMB_MOUNT_PASSWORD_FILE:-${HOME}/.config/smb-nas/password}"

# URL-encodes the characters that would otherwise terminate or re-split the SMB
# URL. '%' is encoded first because it appears in every escape sequence the
# later rules emit; encoding it last would double-encode them. Carried over
# verbatim from the autofs implementation (hardened in #396).
URL_ENCODE_SED='s/%/%25/g; s/@/%40/g; s/:/%3A/g; s/\//%2F/g; s/#/%23/g; s/?/%3F/g; s/&/%26/g; s/ /%20/g; s/+/%2B/g; s/;/%3B/g'

# =============================================================================
# HELPERS
# =============================================================================

log() {
    printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

load_config() {
    if [[ ! -f "${CONFIG_FILE}" ]]; then
        log "✗ Config not found: ${CONFIG_FILE}"
        log "  Run 'rebuild' to generate it from darwin/smb-automount.nix"
        exit 1
    fi

    # shellcheck source=/dev/null
    source "${CONFIG_FILE}"

    # SHARES may be absent entirely; `set -u` would abort on ${#SHARES[@]}.
    if ! declare -p SHARES >/dev/null 2>&1; then
        SHARES=()
    fi

    # shellcheck disable=SC2154  # NAS_HOST/SMB_USERNAME/MOUNT_ROOT come from CONFIG_FILE
    if [[ -z "${NAS_HOST:-}" || -z "${SMB_USERNAME:-}" || -z "${MOUNT_ROOT:-}" || ${#SHARES[@]} -eq 0 ]]; then
        log "✗ Incomplete config in ${CONFIG_FILE} (need NAS_HOST, SMB_USERNAME, MOUNT_ROOT, SHARES)"
        exit 1
    fi
}

# Reads the credential and returns it URL-encoded on stdout.
read_encoded_password() {
    local raw
    raw=$(tr -d '\n' < "${PASSWORD_FILE}")
    if [[ -z "${raw}" ]]; then
        return 1
    fi
    printf '%s\n' "${raw}" | sed -e "${URL_ENCODE_SED}"
}

# The NAS being off, asleep, or off-network is the expected steady state on a
# laptop, so this is a soft check rather than an error path.
nas_reachable() {
    nc -z -w 5 "${NAS_HOST}" 445 >/dev/null 2>&1
}

# Mounts one share. Returns 0 when the share ends up mounted (including when it
# already was), 1 otherwise. Never aborts the run - one dead share must not
# prevent the others from mounting.
mount_share() {
    local share="$1"
    local encoded_password="$2"
    local mount_point="${MOUNT_ROOT}/${share}"

    # Idempotency guard: re-running on the LaunchAgent's timer must be a no-op
    # for shares that are already up, otherwise every tick stacks another mount
    # on the same path. Matched with a quoted pattern rather than `mount | grep`
    # so neither pipefail nor a glob character in the path can skew the answer.
    local mount_table
    mount_table=$(mount)
    if [[ "${mount_table}" == *" on ${mount_point} "* ]]; then
        log "⊘ ${share} already mounted at ${mount_point}"
        return 0
    fi

    if [[ ! -d "${mount_point}" ]] && ! mkdir -p "${mount_point}"; then
        log "✗ ${share}: cannot create mount point ${mount_point}"
        return 1
    fi

    local url="//${SMB_USERNAME}:${encoded_password}@${NAS_HOST}/${share}"
    local output rc=0
    output=$(mount_smbfs "${url}" "${mount_point}" 2>&1) || rc=$?

    if [[ "${rc}" -eq 0 ]]; then
        log "✓ ${share} mounted at ${mount_point}"
        return 0
    fi

    log "✗ ${share}: mount failed (rc=${rc})"
    if [[ -n "${output}" ]]; then
        # mount_smbfs echoes the URL back on some parse failures. Quoting the
        # expansion inside the pattern makes it a literal match, so a password
        # containing glob characters cannot defeat this.
        if [[ "${output}" == *"${encoded_password}"* ]]; then
            output="(suppressed: mount_smbfs output contained the credential)"
        fi
        log "  ${output}"
    fi
    return 1
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    load_config

    if [[ ! -f "${PASSWORD_FILE}" ]]; then
        log "✗ Password file not found: ${PASSWORD_FILE}"
        log "  Create it once: mkdir -p ~/.config/smb-nas"
        log "                  echo 'YOUR_NAS_PASSWORD' > ~/.config/smb-nas/password"
        log "                  chmod 600 ~/.config/smb-nas/password"
        exit 1
    fi

    if ! nas_reachable; then
        log "⊘ ${NAS_HOST}:445 unreachable - skipping mounts, will retry on next tick"
        exit 0
    fi

    local encoded
    if ! encoded=$(read_encoded_password); then
        log "✗ Password file is empty: ${PASSWORD_FILE}"
        exit 1
    fi

    local share failures=0
    for share in "${SHARES[@]}"; do
        mount_share "${share}" "${encoded}" || failures=$((failures + 1))
    done

    if [[ "${failures}" -gt 0 ]]; then
        log "Completed with ${failures} failed mount(s) of ${#SHARES[@]}"
    else
        log "All ${#SHARES[@]} share(s) mounted under ${MOUNT_ROOT}"
    fi

    # Always exit 0 once the config and credential are valid: the agent retries
    # on a timer, and a non-zero exit for a transient NAS hiccup would only add
    # noise to launchd's logs.
    exit 0
}

main "$@"
